##
## Copyright (c) 2023 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
##
## NVIDIA CORPORATION, its affiliates and licensors retain all intellectual
## property and proprietary rights in and to this material, related
## documentation and any modifications thereto. Any use, reproduction,
## disclosure or distribution of this material and related documentation
## without an express license agreement from NVIDIA CORPORATION or
## its affiliates is strictly prohibited.
##
cuboid:
  dummy1:
    dims: [0.01, 0.01, 0.01] # x, y, z
    pose: [0.0, 0.0, -1, 1, 0, 0, 0.0] # x, y, z, qw, qx, qy, qz
cylinder:
  dummy1:
    radius: 0.01
    height: 0.01
    pose: [0.0, 0.0, -0.5, 1, 0, 0, 0.0] # x, y, z, qw, qx, qy, qz
